[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "tracertools"
version = "1.0.0"
authors = [
  { name="Jay Gager", email="jgager@princeton.edu" },
]
description = "A collection of tools for connectomics researchers with a focus on proofreading."
dependencies = [
  "caveclient",
  "cloud-files",
  "cloud-volume",
  "gspread",
  "manifold3d",
  "microviewer",
  "nglui",
  "numpy",
  "osteoid",
  "pandas",
  "plotly",
  "trimesh",
]
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-only"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/jaybgager/tracertools"
Issues = "https://github.com/jaybgager/tracertools/issues"